### ISSUE TITLE
Description component

### ISSUE THREAD

**Issue by wrejcodes** [Gods-Of-ACM/frontendv2#11]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Implement the Description component

![img_1546 3](https://user-images.githubusercontent.com/17745085/39401598-7d1fa94e-4b0e-11e8-9847-d95e53f5ba26.jpg)

**Comment by Quinn-Donnelly** [comment]
Closed by #17
