### ISSUE TITLE
Toggle Component

### ISSUE THREAD

**Issue by wrejcodes** [Gods-Of-ACM/frontendv2#4]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Implement the toggle component
(Add images if possible)
![img_1543 2](https://user-images.githubusercontent.com/17745085/39401509-07bdb6c0-4b0c-11e8-89a3-b219db56d973.jpg)

**Comment by Quinn-Donnelly** [comment]
Resolved via #19
