### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by wrejcodes** [Gods-Of-ACM/frontendv2#6]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Implement the table component.
This is a table implementation of the result list.

**Comment by Quinn-Donnelly** [comment]
This was closed with #18
