### ISSUE TITLE
Navbar Container 

### ISSUE THREAD

**Issue by wrejcodes** [Gods-Of-ACM/frontendv2#7]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Implement the Navbar container 
![img_1544 2](https://user-images.githubusercontent.com/17745085/39401547-280f3196-4b0d-11e8-8601-7c6276019784.jpg)

**Comment by Quinn-Donnelly** [comment]
Only thing not in is the icon to bring home awaiting the icons being brought over from old repo.

**Comment by Quinn-Donnelly** [comment]
#13 Resolves this issue.
