### ISSUE TITLE
Login Card component

### ISSUE THREAD

**Issue by wrejcodes** [Gods-Of-ACM/frontendv2#9]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Implement the login card component. Use the card component from react-bootstrap. This could also implement the registration  component :) 
![img_1546 2](https://user-images.githubusercontent.com/17745085/39401568-b7c5903c-4b0d-11e8-8a5b-cf911a75f522.jpg)

**Comment by Quinn-Donnelly** [comment]
Closed by #15
